name       : openmpi
version    : 3.0.1
release    : 5
source     :
    - https://github.com/open-mpi/ompi/archive/v3.0.1.tar.gz : b5de8e1e1ac70acd4d599ed1112c8ee36df82472e6fb61d9608f75b19dbb2821
license    : BSD-3-Clause
component  : programming.library
summary    : Open Message Passing Interface
description: |
    The Open MPI Project is an open source Message Passing Interface implementation that is developed and maintained by a consortium of academic, research, and industry partners.
setup      : |
    ./autogen.pl
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
