name       : openmpi
version    : 3.0.1
release    : 3
source     :
    - https://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.0.1.tar.bz2 : 663450d1ee7838b03644507e8a76edfb1fba23e601e9e0b5b2a738e54acd785d
license    : BSD-3-Clause
component  : programming.library
summary    : Open Message Passing Interface
description: |
    The Open MPI Project is an open source Message Passing Interface implementation that is developed and maintained by a consortium of academic, research, and industry partners.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
