name       : openmpi
version    : 4.1.2
release    : 7
source     :
    - https://github.com/open-mpi/ompi/archive/refs/tags/v4.1.2.tar.gz : 7c6550531e5615bceb5e695edfbc7efc5b4007288c083152af64997360aa9539
homepage   : https://www.open-mpi.org/
license    : BSD-3-Clause
component  : programming.library
summary    : Open Message Passing Interface
description: |
    The Open MPI Project is an open source Message Passing Interface implementation that is developed and maintained by a consortium of academic, research, and industry partners.
setup      : |
    ./autogen.pl
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
