name       : openmpi
version    : 2.1.0
release    : 1
source     :
    - https://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.0.tar.gz : 265a9c64a468cce464edd069ed8612e1865c5f112f84f4a7a855fb2a0d15e74b
license    : BSD-3-Clause
component  : programming.library
summary    : The Open MPI Project is an open source Message Passing Interface implementation that is developed and maintained by a consortium of academic, research, and industry partners.
description: |
    The Open MPI Project is an open source Message Passing Interface implementation that is developed and maintained by a consortium of academic, research, and industry partners.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
